[tool.poetry]
name = "chatgpt-cli"
version = "0.1.0"
description = "CLI for OpenAI ChatGPT and instruct models."
authors = ["Nick To <nick@nickto.net>"]
license = "MIT"
readme = "README.md"
packages = [{include = "chatgpt_cli"}]

[tool.poetry.scripts]
chatgpt-cli = "chatgpt_cli.main:app"

[tool.poetry.dependencies]
python = "^3.10"
openai = "^0.27.2"
typer = {version = "^0.7.0", extras = ["all"]}
tiktoken = "^0.3.2"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
rope = "^1.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
